# Generated by Django 3.2.18 on 2023-04-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in', to='recipes.amount', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
